language: python

matrix:
    include:
        - python: 2.7
          env: NUMPY_VERSION=1.13

        - python: 3.6
          env: NUMPY_VERSION=1.12

        - python: 3.6
          env: NUMPY_VERSION=1.13 PYGPU=true COVERALLS=true BUILD_DOC=true

sudo: false

addons:
    apt:
        packages:
            libfftw3-dev
            texlive-latex-base
            texlive-latex-recommended
            texlive-latex-extra
            dvipng


# Setup numpy + scipy using miniconda
# See http://conda.pydata.org/docs/travis.html
install:
    # Install miniconda according to Python version of the build (saves downloading if versions match)
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # Install dependencies and enter test environment
    - conda create -n testenv python=$TRAVIS_PYTHON_VERSION nomkl "numpy=$NUMPY_VERSION" scipy future sphinx sphinx_rtd_theme pytest pytest-pep8 pytest-cov
    - source activate testenv
    # We avoid annoying issues with building pyfftw wheels by using a conda-forge version
    - conda install pywavelets scikit-image
    - conda install -c conda-forge pyfftw
    - if [[ "$PYGPU" == "true" ]]; then
        conda install pygpu;
      fi

    # Not on conda, need to use pip
    - pip install travis-sphinx

    # Install our package
    - pip install -e .


before_script:
    - pip install -r test_requirements.txt

script:
    # Run tests, including PEP8 check, and produce a coverage report
    - pytest --doctest-modules --cov --cov-report term-missing --pep8 $TRAVIS_BUILD_DIR/odl || exit -1
    # Invoke also the alternative way of running the unit tests
    - python -c "import odl; odl.test()" || exit -1
    # Build the Sphinx doc (only for Python 3.6, master branch, no PR)
    # To avoid clogging the logs, we redirect stderr to /dev/null
    - if [[ "BUILD_DOC" == "true" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        cd $TRAVIS_BUILD_DIR/doc/source && python generate_doc.py && cd -;
        travis-sphinx -n -s $TRAVIS_BUILD_DIR/doc/source build 2>/dev/null;
      fi

after_success:
    # Push coverage report to coveralls
    - if [[ "$COVERALLS" == "true" ]]; then
        coveralls;
      fi
    # Deploy the Sphinx doc to gh-pages (only for Python 3.6, master branch, no PR)
    # See https://github.com/Syntaf/travis-sphinx
    - if [[ "BUILD_DOC" == "true" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        travis-sphinx deploy;
      fi
