package:
    name: odl
    version: "0.7.0"

source:
    git_url: https://github.com/odlgroup/odl
    git_rev: v0.7.0

build:
    number: 0
    # noarch_python: True

requirements:
    build:
        - python
        - setuptools

    host:
        - nomkl # [not win]
        - future >=0.14
        - numpy >=1.10
        - scipy >=0.14
        - pytest >=3.0.3,<=3.7

    run:
        - python
        - future >=0.14
        - numpy >=1.10
        - scipy >=0.14
        - matplotlib

test:
    imports:
        - odl
    commands:
        - python -c "import odl; odl.test()"

about:
    home: https://github.com/odlgroup/odl
    license: MPL-2.0
    license_file: LICENSE
    summary: "Operator Discretization Library - a versatile Python framework for rapid prototyping in Inverse Problems and related fields"

extra:
    maintainers:
        - Jonas Adler (@adler-j)
        - Holger Kohr (@kohr-h)
